@ControleFinanceiro_HostAddress = http://localhost:5096

GET {{ControleFinanceiro_HostAddress}}/api/Categoria/3
Accept: application/json

###

GET {{ControleFinanceiro_HostAddress}}/api/Categoria
Accept: application/json

###

POST {{ControleFinanceiro_HostAddress}}/api/Categoria
Content-Type: application/json
Accept: application/json

{
  "nome": "Teste"
}

###

PATCH {{ControleFinanceiro_HostAddress}}/api/Categoria/3
Content-Type: application/json
Accept: application/json

{
  "nome": "Testerr"
}

###

DELETE {{ControleFinanceiro_HostAddress}}/api/Categoria/2
Accept: application/json

###

###  MOVIMENTACOES

POST {{ControleFinanceiro_HostAddress}}/api/Movimentacao
Content-Type: application/json
Accept: application/json

{
  "valor": 12.0,
  "tipo": "Despesa",
  "categoriaId": 3,
  "data": "2026-06-22"
}

###

GET {{ControleFinanceiro_HostAddress}}/api/Movimentacao/2
Accept: application/json

###

GET {{ControleFinanceiro_HostAddress}}/api/Movimentacao
Accept: application/json

###

DELETE {{ControleFinanceiro_HostAddress}}/api/Movimentacao/1
Accept: application/json